/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_shetj_speex_SpeexUtils */

#ifndef _Included_me_shetj_speex_SpeexUtils
#define _Included_me_shetj_speex_SpeexUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef me_shetj_speex_SpeexUtils_DEFAULT_COMPRESSION
#define me_shetj_speex_SpeexUtils_DEFAULT_COMPRESSION 4L
/*
 * Class:     me_shetj_speex_SpeexUtils
 * Method:    open
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_me_shetj_speex_SpeexUtils_open
  (JNIEnv *, jobject, jint);

/*
 * Class:     me_shetj_speex_SpeexUtils
 * Method:    getFrameSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_shetj_speex_SpeexUtils_getFrameSize
  (JNIEnv *, jobject);

/*
 * Class:     me_shetj_speex_SpeexUtils
 * Method:    decode
 * Signature: ([B[SI)I
 */
JNIEXPORT jint JNICALL Java_me_shetj_speex_SpeexUtils_decode
  (JNIEnv *, jobject, jbyteArray, jshortArray, jint);

/*
 * Class:     me_shetj_speex_SpeexUtils
 * Method:    encode
 * Signature: ([SI[BI)I
 */
JNIEXPORT jint JNICALL Java_me_shetj_speex_SpeexUtils_encode
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray, jint);

/*
 * Class:     me_shetj_speex_SpeexUtils
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_shetj_speex_SpeexUtils_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
